from tkinter import *
root=Tk()
root.title('My tk app')
root.geometry('400x300')
root.config(bg='cyan')
l1=Label(root,text='Welcome to Tkinter',bg='cyan',fg='white',font=('Arial',20),padx=10,pady=10)
l1.pack()
l2=Label(root,text='Enter your name',bg='light blue',fg='white')
l2.pack()
e1=Entry(root)
e1.pack()
r=IntVar()
l4=Label(root,text='Select your gender:')
l4.pack()
r1=Radiobutton(root,text='Male',variable=r,value=1)
r1.pack()
r2=Radiobutton(root,text='Female',variable=r,value=2)
r2.pack()
def msg():
    s1=e1.get()
    s2='Hey '+s1+'. Nice to meet you'
    l3=Label(root,text=s2)
    l3.pack()
b1=Button(root,text='Submit',bg='light blue',fg='white',command=msg)
b1.pack()

root.mainloop()